#!/bin/bash
# Regenerate src/ffi.rs from librados.h. Run only when the librados version changes.
# Usage: hack/bindgen.sh [path to ceph source tree]
set -euo pipefail

CEPH_SRC="${1:-$(dirname "$0")/../../references/ceph/ceph}"
INCLUDE="${CEPH_SRC}/src/include"
OUT="$(dirname "$0")/../src/ffi.rs"
# libclang needs its builtin headers (stddef.h); clang-resource-filesystem installs them here.
CLANG_INCLUDE="$(dirname "$(find /usr/lib/clang /usr/lib64/clang -name stddef.h 2>/dev/null | head -1)")"

bindgen "${INCLUDE}/rados/librados.h" \
    --allowlist-function 'rados_.*' \
    --allowlist-type 'rados_.*' \
    --allowlist-type 'librados_cmpxattr_op' \
    --allowlist-var 'LIBRADOS_.*' \
    --default-enum-style moduleconsts \
    --no-doc-comments \
    --raw-line '#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case, dead_code, clippy::all)]' \
    --raw-line "// Generated by hack/bindgen.sh from ceph $(git -C "${CEPH_SRC}" rev-parse --short HEAD); do not edit." \
    --output "${OUT}" \
    -- -I "${INCLUDE}" -isystem "${CLANG_INCLUDE}"

rustfmt --edition 2021 "${OUT}"
