/* automatically generated by rust-bindgen 0.72.1 */

#![allow(
    non_camel_case_types,
    non_upper_case_globals,
    non_snake_case,
    dead_code,
    clippy::all
)]
// Generated by hack/bindgen.sh from ceph 7140eeecfb9; do not edit.

pub const LIBRADOS_ALL_NSPACES: &[u8; 2] = b"\x01\0";
pub const LIBRADOS_VER_MAJOR: u32 = 3;
pub const LIBRADOS_VER_MINOR: u32 = 0;
pub const LIBRADOS_VER_EXTRA: u32 = 0;
pub const LIBRADOS_SUPPORTS_WATCH: u32 = 1;
pub const LIBRADOS_SUPPORTS_SERVICES: u32 = 1;
pub const LIBRADOS_SUPPORTS_GETADDRS: u32 = 1;
pub const LIBRADOS_SUPPORTS_APP_METADATA: u32 = 1;
pub const LIBRADOS_LOCK_FLAG_RENEW: u32 = 1;
pub const LIBRADOS_LOCK_FLAG_MAY_RENEW: u32 = 1;
pub const LIBRADOS_LOCK_FLAG_MUST_RENEW: u32 = 2;
pub const LIBRADOS_CREATE_EXCLUSIVE: u32 = 1;
pub const LIBRADOS_CREATE_IDEMPOTENT: u32 = 0;
pub type __time_t = ::std::os::raw::c_long;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type time_t = __time_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timeval {
    pub tv_sec: __time_t,
    pub tv_usec: __suseconds_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of timeval"][::std::mem::size_of::<timeval>() - 16usize];
    ["Alignment of timeval"][::std::mem::align_of::<timeval>() - 8usize];
    ["Offset of field: timeval::tv_sec"][::std::mem::offset_of!(timeval, tv_sec) - 0usize];
    ["Offset of field: timeval::tv_usec"][::std::mem::offset_of!(timeval, tv_usec) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timespec {
    pub tv_sec: __time_t,
    pub tv_nsec: __syscall_slong_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of timespec"][::std::mem::size_of::<timespec>() - 16usize];
    ["Alignment of timespec"][::std::mem::align_of::<timespec>() - 8usize];
    ["Offset of field: timespec::tv_sec"][::std::mem::offset_of!(timespec, tv_sec) - 0usize];
    ["Offset of field: timespec::tv_nsec"][::std::mem::offset_of!(timespec, tv_nsec) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct notify_ack_t {
    pub notifier_id: u64,
    pub cookie: u64,
    pub payload: *mut ::std::os::raw::c_char,
    pub payload_len: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of notify_ack_t"][::std::mem::size_of::<notify_ack_t>() - 32usize];
    ["Alignment of notify_ack_t"][::std::mem::align_of::<notify_ack_t>() - 8usize];
    ["Offset of field: notify_ack_t::notifier_id"]
        [::std::mem::offset_of!(notify_ack_t, notifier_id) - 0usize];
    ["Offset of field: notify_ack_t::cookie"]
        [::std::mem::offset_of!(notify_ack_t, cookie) - 8usize];
    ["Offset of field: notify_ack_t::payload"]
        [::std::mem::offset_of!(notify_ack_t, payload) - 16usize];
    ["Offset of field: notify_ack_t::payload_len"]
        [::std::mem::offset_of!(notify_ack_t, payload_len) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct notify_timeout_t {
    pub notifier_id: u64,
    pub cookie: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of notify_timeout_t"][::std::mem::size_of::<notify_timeout_t>() - 16usize];
    ["Alignment of notify_timeout_t"][::std::mem::align_of::<notify_timeout_t>() - 8usize];
    ["Offset of field: notify_timeout_t::notifier_id"]
        [::std::mem::offset_of!(notify_timeout_t, notifier_id) - 0usize];
    ["Offset of field: notify_timeout_t::cookie"]
        [::std::mem::offset_of!(notify_timeout_t, cookie) - 8usize];
};
pub mod librados_cmpxattr_op {
    pub type Type = ::std::os::raw::c_uint;
    pub const LIBRADOS_CMPXATTR_OP_EQ: Type = 1;
    pub const LIBRADOS_CMPXATTR_OP_NE: Type = 2;
    pub const LIBRADOS_CMPXATTR_OP_GT: Type = 3;
    pub const LIBRADOS_CMPXATTR_OP_GTE: Type = 4;
    pub const LIBRADOS_CMPXATTR_OP_LT: Type = 5;
    pub const LIBRADOS_CMPXATTR_OP_LTE: Type = 6;
}
pub mod rados_checksum_type_t {
    pub type Type = ::std::os::raw::c_uint;
    pub const LIBRADOS_CHECKSUM_TYPE_XXHASH32: Type = 0;
    pub const LIBRADOS_CHECKSUM_TYPE_XXHASH64: Type = 1;
    pub const LIBRADOS_CHECKSUM_TYPE_CRC32C: Type = 2;
}
pub type rados_t = *mut ::std::os::raw::c_void;
pub type rados_config_t = *mut ::std::os::raw::c_void;
pub type rados_ioctx_t = *mut ::std::os::raw::c_void;
pub type rados_list_ctx_t = *mut ::std::os::raw::c_void;
pub type rados_object_list_cursor = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rados_object_list_item {
    pub oid_length: usize,
    pub oid: *mut ::std::os::raw::c_char,
    pub nspace_length: usize,
    pub nspace: *mut ::std::os::raw::c_char,
    pub locator_length: usize,
    pub locator: *mut ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rados_object_list_item"][::std::mem::size_of::<rados_object_list_item>() - 48usize];
    ["Alignment of rados_object_list_item"]
        [::std::mem::align_of::<rados_object_list_item>() - 8usize];
    ["Offset of field: rados_object_list_item::oid_length"]
        [::std::mem::offset_of!(rados_object_list_item, oid_length) - 0usize];
    ["Offset of field: rados_object_list_item::oid"]
        [::std::mem::offset_of!(rados_object_list_item, oid) - 8usize];
    ["Offset of field: rados_object_list_item::nspace_length"]
        [::std::mem::offset_of!(rados_object_list_item, nspace_length) - 16usize];
    ["Offset of field: rados_object_list_item::nspace"]
        [::std::mem::offset_of!(rados_object_list_item, nspace) - 24usize];
    ["Offset of field: rados_object_list_item::locator_length"]
        [::std::mem::offset_of!(rados_object_list_item, locator_length) - 32usize];
    ["Offset of field: rados_object_list_item::locator"]
        [::std::mem::offset_of!(rados_object_list_item, locator) - 40usize];
};
pub type rados_snap_t = u64;
pub type rados_xattrs_iter_t = *mut ::std::os::raw::c_void;
pub type rados_omap_iter_t = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rados_pool_stat_t {
    pub num_bytes: u64,
    pub num_kb: u64,
    pub num_objects: u64,
    pub num_object_clones: u64,
    pub num_object_copies: u64,
    pub num_objects_missing_on_primary: u64,
    pub num_objects_unfound: u64,
    pub num_objects_degraded: u64,
    pub num_rd: u64,
    pub num_rd_kb: u64,
    pub num_wr: u64,
    pub num_wr_kb: u64,
    pub num_user_bytes: u64,
    pub compressed_bytes_orig: u64,
    pub compressed_bytes: u64,
    pub compressed_bytes_alloc: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rados_pool_stat_t"][::std::mem::size_of::<rados_pool_stat_t>() - 128usize];
    ["Alignment of rados_pool_stat_t"][::std::mem::align_of::<rados_pool_stat_t>() - 8usize];
    ["Offset of field: rados_pool_stat_t::num_bytes"]
        [::std::mem::offset_of!(rados_pool_stat_t, num_bytes) - 0usize];
    ["Offset of field: rados_pool_stat_t::num_kb"]
        [::std::mem::offset_of!(rados_pool_stat_t, num_kb) - 8usize];
    ["Offset of field: rados_pool_stat_t::num_objects"]
        [::std::mem::offset_of!(rados_pool_stat_t, num_objects) - 16usize];
    ["Offset of field: rados_pool_stat_t::num_object_clones"]
        [::std::mem::offset_of!(rados_pool_stat_t, num_object_clones) - 24usize];
    ["Offset of field: rados_pool_stat_t::num_object_copies"]
        [::std::mem::offset_of!(rados_pool_stat_t, num_object_copies) - 32usize];
    ["Offset of field: rados_pool_stat_t::num_objects_missing_on_primary"]
        [::std::mem::offset_of!(rados_pool_stat_t, num_objects_missing_on_primary) - 40usize];
    ["Offset of field: rados_pool_stat_t::num_objects_unfound"]
        [::std::mem::offset_of!(rados_pool_stat_t, num_objects_unfound) - 48usize];
    ["Offset of field: rados_pool_stat_t::num_objects_degraded"]
        [::std::mem::offset_of!(rados_pool_stat_t, num_objects_degraded) - 56usize];
    ["Offset of field: rados_pool_stat_t::num_rd"]
        [::std::mem::offset_of!(rados_pool_stat_t, num_rd) - 64usize];
    ["Offset of field: rados_pool_stat_t::num_rd_kb"]
        [::std::mem::offset_of!(rados_pool_stat_t, num_rd_kb) - 72usize];
    ["Offset of field: rados_pool_stat_t::num_wr"]
        [::std::mem::offset_of!(rados_pool_stat_t, num_wr) - 80usize];
    ["Offset of field: rados_pool_stat_t::num_wr_kb"]
        [::std::mem::offset_of!(rados_pool_stat_t, num_wr_kb) - 88usize];
    ["Offset of field: rados_pool_stat_t::num_user_bytes"]
        [::std::mem::offset_of!(rados_pool_stat_t, num_user_bytes) - 96usize];
    ["Offset of field: rados_pool_stat_t::compressed_bytes_orig"]
        [::std::mem::offset_of!(rados_pool_stat_t, compressed_bytes_orig) - 104usize];
    ["Offset of field: rados_pool_stat_t::compressed_bytes"]
        [::std::mem::offset_of!(rados_pool_stat_t, compressed_bytes) - 112usize];
    ["Offset of field: rados_pool_stat_t::compressed_bytes_alloc"]
        [::std::mem::offset_of!(rados_pool_stat_t, compressed_bytes_alloc) - 120usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rados_cluster_stat_t {
    pub kb: u64,
    pub kb_used: u64,
    pub kb_avail: u64,
    pub num_objects: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rados_cluster_stat_t"][::std::mem::size_of::<rados_cluster_stat_t>() - 32usize];
    ["Alignment of rados_cluster_stat_t"][::std::mem::align_of::<rados_cluster_stat_t>() - 8usize];
    ["Offset of field: rados_cluster_stat_t::kb"]
        [::std::mem::offset_of!(rados_cluster_stat_t, kb) - 0usize];
    ["Offset of field: rados_cluster_stat_t::kb_used"]
        [::std::mem::offset_of!(rados_cluster_stat_t, kb_used) - 8usize];
    ["Offset of field: rados_cluster_stat_t::kb_avail"]
        [::std::mem::offset_of!(rados_cluster_stat_t, kb_avail) - 16usize];
    ["Offset of field: rados_cluster_stat_t::num_objects"]
        [::std::mem::offset_of!(rados_cluster_stat_t, num_objects) - 24usize];
};
pub type rados_write_op_t = *mut ::std::os::raw::c_void;
pub type rados_read_op_t = *mut ::std::os::raw::c_void;
pub type rados_completion_t = *mut ::std::os::raw::c_void;
unsafe extern "C" {
    pub fn rados_version(
        major: *mut ::std::os::raw::c_int,
        minor: *mut ::std::os::raw::c_int,
        extra: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_create(
        cluster: *mut rados_t,
        id: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_create2(
        pcluster: *mut rados_t,
        clustername: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        flags: u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_create_with_context(
        cluster: *mut rados_t,
        cct: rados_config_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ping_monitor(
        cluster: rados_t,
        mon_id: *const ::std::os::raw::c_char,
        outstr: *mut *mut ::std::os::raw::c_char,
        outstrlen: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_connect(cluster: rados_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_shutdown(cluster: rados_t);
}
unsafe extern "C" {
    pub fn rados_conf_read_file(
        cluster: rados_t,
        path: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_conf_parse_argv(
        cluster: rados_t,
        argc: ::std::os::raw::c_int,
        argv: *mut *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_conf_parse_argv_remainder(
        cluster: rados_t,
        argc: ::std::os::raw::c_int,
        argv: *mut *const ::std::os::raw::c_char,
        remargv: *mut *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_conf_parse_env(
        cluster: rados_t,
        var: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_conf_set(
        cluster: rados_t,
        option: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_conf_get(
        cluster: rados_t,
        option: *const ::std::os::raw::c_char,
        buf: *mut ::std::os::raw::c_char,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_cluster_stat(
        cluster: rados_t,
        result: *mut rados_cluster_stat_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_cluster_fsid(
        cluster: rados_t,
        buf: *mut ::std::os::raw::c_char,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_wait_for_latest_osdmap(cluster: rados_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_pool_list(
        cluster: rados_t,
        buf: *mut ::std::os::raw::c_char,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_inconsistent_pg_list(
        cluster: rados_t,
        pool: i64,
        buf: *mut ::std::os::raw::c_char,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_cct(cluster: rados_t) -> rados_config_t;
}
unsafe extern "C" {
    pub fn rados_get_instance_id(cluster: rados_t) -> u64;
}
unsafe extern "C" {
    pub fn rados_get_min_compatible_osd(
        cluster: rados_t,
        require_osd_release: *mut i8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_get_min_compatible_client(
        cluster: rados_t,
        min_compat_client: *mut i8,
        require_min_compat_client: *mut i8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_create(
        cluster: rados_t,
        pool_name: *const ::std::os::raw::c_char,
        ioctx: *mut rados_ioctx_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_create2(
        cluster: rados_t,
        pool_id: i64,
        ioctx: *mut rados_ioctx_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_destroy(io: rados_ioctx_t);
}
unsafe extern "C" {
    pub fn rados_ioctx_cct(io: rados_ioctx_t) -> rados_config_t;
}
unsafe extern "C" {
    pub fn rados_ioctx_get_cluster(io: rados_ioctx_t) -> rados_t;
}
unsafe extern "C" {
    pub fn rados_ioctx_pool_stat(
        io: rados_ioctx_t,
        stats: *mut rados_pool_stat_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_pool_lookup(cluster: rados_t, pool_name: *const ::std::os::raw::c_char) -> i64;
}
unsafe extern "C" {
    pub fn rados_pool_reverse_lookup(
        cluster: rados_t,
        id: i64,
        buf: *mut ::std::os::raw::c_char,
        maxlen: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_pool_create(
        cluster: rados_t,
        pool_name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_pool_create_with_auid(
        cluster: rados_t,
        pool_name: *const ::std::os::raw::c_char,
        auid: u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_pool_create_with_crush_rule(
        cluster: rados_t,
        pool_name: *const ::std::os::raw::c_char,
        crush_rule_num: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_pool_create_with_all(
        cluster: rados_t,
        pool_name: *const ::std::os::raw::c_char,
        auid: u64,
        crush_rule_num: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_pool_get_base_tier(
        cluster: rados_t,
        pool: i64,
        base_tier: *mut i64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_pool_delete(
        cluster: rados_t,
        pool_name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_pool_set_auid(io: rados_ioctx_t, auid: u64) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_pool_get_auid(io: rados_ioctx_t, auid: *mut u64) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_pool_requires_alignment(io: rados_ioctx_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_pool_requires_alignment2(
        io: rados_ioctx_t,
        req: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_pool_required_alignment(io: rados_ioctx_t) -> u64;
}
unsafe extern "C" {
    pub fn rados_ioctx_pool_required_alignment2(
        io: rados_ioctx_t,
        alignment: *mut u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_get_id(io: rados_ioctx_t) -> i64;
}
unsafe extern "C" {
    pub fn rados_ioctx_get_pool_name(
        io: rados_ioctx_t,
        buf: *mut ::std::os::raw::c_char,
        maxlen: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_locator_set_key(io: rados_ioctx_t, key: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn rados_ioctx_set_namespace(io: rados_ioctx_t, nspace: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn rados_ioctx_get_namespace(
        io: rados_ioctx_t,
        buf: *mut ::std::os::raw::c_char,
        maxlen: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_nobjects_list_open(
        io: rados_ioctx_t,
        ctx: *mut rados_list_ctx_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_nobjects_list_get_pg_hash_position(ctx: rados_list_ctx_t) -> u32;
}
unsafe extern "C" {
    pub fn rados_nobjects_list_seek(ctx: rados_list_ctx_t, pos: u32) -> u32;
}
unsafe extern "C" {
    pub fn rados_nobjects_list_seek_cursor(
        ctx: rados_list_ctx_t,
        cursor: rados_object_list_cursor,
    ) -> u32;
}
unsafe extern "C" {
    pub fn rados_nobjects_list_get_cursor(
        ctx: rados_list_ctx_t,
        cursor: *mut rados_object_list_cursor,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_nobjects_list_next(
        ctx: rados_list_ctx_t,
        entry: *mut *const ::std::os::raw::c_char,
        key: *mut *const ::std::os::raw::c_char,
        nspace: *mut *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_nobjects_list_next2(
        ctx: rados_list_ctx_t,
        entry: *mut *const ::std::os::raw::c_char,
        key: *mut *const ::std::os::raw::c_char,
        nspace: *mut *const ::std::os::raw::c_char,
        entry_size: *mut usize,
        key_size: *mut usize,
        nspace_size: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_nobjects_list_close(ctx: rados_list_ctx_t);
}
unsafe extern "C" {
    pub fn rados_object_list_begin(io: rados_ioctx_t) -> rados_object_list_cursor;
}
unsafe extern "C" {
    pub fn rados_object_list_end(io: rados_ioctx_t) -> rados_object_list_cursor;
}
unsafe extern "C" {
    pub fn rados_object_list_is_end(
        io: rados_ioctx_t,
        cur: rados_object_list_cursor,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_object_list_cursor_free(io: rados_ioctx_t, cur: rados_object_list_cursor);
}
unsafe extern "C" {
    pub fn rados_object_list_cursor_cmp(
        io: rados_ioctx_t,
        lhs: rados_object_list_cursor,
        rhs: rados_object_list_cursor,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_object_list(
        io: rados_ioctx_t,
        start: rados_object_list_cursor,
        finish: rados_object_list_cursor,
        result_size: usize,
        filter_buf: *const ::std::os::raw::c_char,
        filter_buf_len: usize,
        results: *mut rados_object_list_item,
        next: *mut rados_object_list_cursor,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_object_list_free(result_size: usize, results: *mut rados_object_list_item);
}
unsafe extern "C" {
    pub fn rados_object_list_slice(
        io: rados_ioctx_t,
        start: rados_object_list_cursor,
        finish: rados_object_list_cursor,
        n: usize,
        m: usize,
        split_start: *mut rados_object_list_cursor,
        split_finish: *mut rados_object_list_cursor,
    );
}
unsafe extern "C" {
    pub fn rados_ioctx_snap_create(
        io: rados_ioctx_t,
        snapname: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_snap_remove(
        io: rados_ioctx_t,
        snapname: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_snap_rollback(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        snapname: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_rollback(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        snapname: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_snap_set_read(io: rados_ioctx_t, snap: rados_snap_t);
}
unsafe extern "C" {
    pub fn rados_ioctx_selfmanaged_snap_create(
        io: rados_ioctx_t,
        snapid: *mut rados_snap_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_ioctx_selfmanaged_snap_create(
        io: rados_ioctx_t,
        snapid: *mut rados_snap_t,
        completion: rados_completion_t,
    );
}
unsafe extern "C" {
    pub fn rados_ioctx_selfmanaged_snap_remove(
        io: rados_ioctx_t,
        snapid: rados_snap_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_ioctx_selfmanaged_snap_remove(
        io: rados_ioctx_t,
        snapid: rados_snap_t,
        completion: rados_completion_t,
    );
}
unsafe extern "C" {
    pub fn rados_ioctx_selfmanaged_snap_rollback(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        snapid: rados_snap_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_selfmanaged_snap_set_write_ctx(
        io: rados_ioctx_t,
        seq: rados_snap_t,
        snaps: *mut rados_snap_t,
        num_snaps: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_snap_list(
        io: rados_ioctx_t,
        snaps: *mut rados_snap_t,
        maxlen: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_snap_lookup(
        io: rados_ioctx_t,
        name: *const ::std::os::raw::c_char,
        id: *mut rados_snap_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_snap_get_name(
        io: rados_ioctx_t,
        id: rados_snap_t,
        name: *mut ::std::os::raw::c_char,
        maxlen: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_ioctx_snap_get_stamp(
        io: rados_ioctx_t,
        id: rados_snap_t,
        t: *mut time_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_get_last_version(io: rados_ioctx_t) -> u64;
}
unsafe extern "C" {
    pub fn rados_write(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        buf: *const ::std::os::raw::c_char,
        len: usize,
        off: u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_write_full(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        buf: *const ::std::os::raw::c_char,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_writesame(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        buf: *const ::std::os::raw::c_char,
        data_len: usize,
        write_len: usize,
        off: u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_append(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        buf: *const ::std::os::raw::c_char,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_read(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        buf: *mut ::std::os::raw::c_char,
        len: usize,
        off: u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_checksum(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        type_: rados_checksum_type_t::Type,
        init_value: *const ::std::os::raw::c_char,
        init_value_len: usize,
        len: usize,
        off: u64,
        chunk_size: usize,
        pchecksum: *mut ::std::os::raw::c_char,
        checksum_len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_remove(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_trunc(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        size: u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_cmpext(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        cmp_buf: *const ::std::os::raw::c_char,
        cmp_len: usize,
        off: u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_getxattr(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        buf: *mut ::std::os::raw::c_char,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_setxattr(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        buf: *const ::std::os::raw::c_char,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_rmxattr(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_getxattrs(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        iter: *mut rados_xattrs_iter_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_getxattrs_next(
        iter: rados_xattrs_iter_t,
        name: *mut *const ::std::os::raw::c_char,
        val: *mut *const ::std::os::raw::c_char,
        len: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_getxattrs_end(iter: rados_xattrs_iter_t);
}
unsafe extern "C" {
    pub fn rados_omap_get_next(
        iter: rados_omap_iter_t,
        key: *mut *mut ::std::os::raw::c_char,
        val: *mut *mut ::std::os::raw::c_char,
        len: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_omap_get_next2(
        iter: rados_omap_iter_t,
        key: *mut *mut ::std::os::raw::c_char,
        val: *mut *mut ::std::os::raw::c_char,
        key_len: *mut usize,
        val_len: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_omap_iter_size(iter: rados_omap_iter_t) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn rados_omap_get_end(iter: rados_omap_iter_t);
}
unsafe extern "C" {
    pub fn rados_stat(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        psize: *mut u64,
        pmtime: *mut time_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_stat2(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        psize: *mut u64,
        pmtime: *mut timespec,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_exec(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        cls: *const ::std::os::raw::c_char,
        method: *const ::std::os::raw::c_char,
        in_buf: *const ::std::os::raw::c_char,
        in_len: usize,
        buf: *mut ::std::os::raw::c_char,
        out_len: usize,
    ) -> ::std::os::raw::c_int;
}
pub type rados_callback_t = ::std::option::Option<
    unsafe extern "C" fn(cb: rados_completion_t, arg: *mut ::std::os::raw::c_void),
>;
unsafe extern "C" {
    pub fn rados_aio_create_completion(
        cb_arg: *mut ::std::os::raw::c_void,
        cb_complete: rados_callback_t,
        cb_safe: rados_callback_t,
        pc: *mut rados_completion_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_create_completion2(
        cb_arg: *mut ::std::os::raw::c_void,
        cb_complete: rados_callback_t,
        pc: *mut rados_completion_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_wait_for_complete(c: rados_completion_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_wait_for_safe(c: rados_completion_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_is_complete(c: rados_completion_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_is_safe(c: rados_completion_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_wait_for_complete_and_cb(c: rados_completion_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_wait_for_safe_and_cb(c: rados_completion_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_is_complete_and_cb(c: rados_completion_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_is_safe_and_cb(c: rados_completion_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_get_return_value(c: rados_completion_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_get_version(c: rados_completion_t) -> u64;
}
unsafe extern "C" {
    pub fn rados_aio_release(c: rados_completion_t);
}
unsafe extern "C" {
    pub fn rados_aio_write(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
        buf: *const ::std::os::raw::c_char,
        len: usize,
        off: u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_append(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
        buf: *const ::std::os::raw::c_char,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_write_full(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
        buf: *const ::std::os::raw::c_char,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_writesame(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
        buf: *const ::std::os::raw::c_char,
        data_len: usize,
        write_len: usize,
        off: u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_remove(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_read(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
        buf: *mut ::std::os::raw::c_char,
        len: usize,
        off: u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_flush(io: rados_ioctx_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_flush_async(
        io: rados_ioctx_t,
        completion: rados_completion_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_stat(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
        psize: *mut u64,
        pmtime: *mut time_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_stat2(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
        psize: *mut u64,
        pmtime: *mut timespec,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_cmpext(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
        cmp_buf: *const ::std::os::raw::c_char,
        cmp_len: usize,
        off: u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_cancel(
        io: rados_ioctx_t,
        completion: rados_completion_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_exec(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
        cls: *const ::std::os::raw::c_char,
        method: *const ::std::os::raw::c_char,
        in_buf: *const ::std::os::raw::c_char,
        in_len: usize,
        buf: *mut ::std::os::raw::c_char,
        out_len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_getxattr(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
        name: *const ::std::os::raw::c_char,
        buf: *mut ::std::os::raw::c_char,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_setxattr(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
        name: *const ::std::os::raw::c_char,
        buf: *const ::std::os::raw::c_char,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_rmxattr(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
        name: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_getxattrs(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
        iter: *mut rados_xattrs_iter_t,
    ) -> ::std::os::raw::c_int;
}
pub type rados_watchcb_t = ::std::option::Option<
    unsafe extern "C" fn(opcode: u8, ver: u64, arg: *mut ::std::os::raw::c_void),
>;
pub type rados_watchcb2_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg: *mut ::std::os::raw::c_void,
        notify_id: u64,
        handle: u64,
        notifier_id: u64,
        data: *mut ::std::os::raw::c_void,
        data_len: usize,
    ),
>;
pub type rados_watcherrcb_t = ::std::option::Option<
    unsafe extern "C" fn(pre: *mut ::std::os::raw::c_void, cookie: u64, err: ::std::os::raw::c_int),
>;
unsafe extern "C" {
    pub fn rados_watch(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        ver: u64,
        cookie: *mut u64,
        watchcb: rados_watchcb_t,
        arg: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_watch2(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        cookie: *mut u64,
        watchcb: rados_watchcb2_t,
        watcherrcb: rados_watcherrcb_t,
        arg: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_watch3(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        cookie: *mut u64,
        watchcb: rados_watchcb2_t,
        watcherrcb: rados_watcherrcb_t,
        timeout: u32,
        arg: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_watch(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
        handle: *mut u64,
        watchcb: rados_watchcb2_t,
        watcherrcb: rados_watcherrcb_t,
        arg: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_watch2(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
        handle: *mut u64,
        watchcb: rados_watchcb2_t,
        watcherrcb: rados_watcherrcb_t,
        timeout: u32,
        arg: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_watch_check(io: rados_ioctx_t, cookie: u64) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_unwatch(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        cookie: u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_unwatch2(io: rados_ioctx_t, cookie: u64) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_unwatch(
        io: rados_ioctx_t,
        cookie: u64,
        completion: rados_completion_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_notify(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        ver: u64,
        buf: *const ::std::os::raw::c_char,
        buf_len: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_notify(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
        buf: *const ::std::os::raw::c_char,
        buf_len: ::std::os::raw::c_int,
        timeout_ms: u64,
        reply_buffer: *mut *mut ::std::os::raw::c_char,
        reply_buffer_len: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_notify2(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        buf: *const ::std::os::raw::c_char,
        buf_len: ::std::os::raw::c_int,
        timeout_ms: u64,
        reply_buffer: *mut *mut ::std::os::raw::c_char,
        reply_buffer_len: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_decode_notify_response(
        reply_buffer: *mut ::std::os::raw::c_char,
        reply_buffer_len: usize,
        acks: *mut *mut notify_ack_t,
        nr_acks: *mut usize,
        timeouts: *mut *mut notify_timeout_t,
        nr_timeouts: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_free_notify_response(
        acks: *mut notify_ack_t,
        nr_acks: usize,
        timeouts: *mut notify_timeout_t,
    );
}
unsafe extern "C" {
    pub fn rados_notify_ack(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        notify_id: u64,
        cookie: u64,
        buf: *const ::std::os::raw::c_char,
        buf_len: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_watch_flush(cluster: rados_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_watch_flush(
        cluster: rados_t,
        completion: rados_completion_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_cache_pin(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_cache_unpin(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_set_alloc_hint(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        expected_object_size: u64,
        expected_write_size: u64,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_set_alloc_hint2(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        expected_object_size: u64,
        expected_write_size: u64,
        flags: u32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_create_write_op() -> rados_write_op_t;
}
unsafe extern "C" {
    pub fn rados_release_write_op(write_op: rados_write_op_t);
}
unsafe extern "C" {
    pub fn rados_write_op_set_flags(write_op: rados_write_op_t, flags: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn rados_write_op_assert_exists(write_op: rados_write_op_t);
}
unsafe extern "C" {
    pub fn rados_write_op_assert_version(write_op: rados_write_op_t, ver: u64);
}
unsafe extern "C" {
    pub fn rados_write_op_cmpext(
        write_op: rados_write_op_t,
        cmp_buf: *const ::std::os::raw::c_char,
        cmp_len: usize,
        off: u64,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_cmpxattr(
        write_op: rados_write_op_t,
        name: *const ::std::os::raw::c_char,
        comparison_operator: u8,
        value: *const ::std::os::raw::c_char,
        value_len: usize,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_omap_cmp(
        write_op: rados_write_op_t,
        key: *const ::std::os::raw::c_char,
        comparison_operator: u8,
        val: *const ::std::os::raw::c_char,
        val_len: usize,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_omap_cmp2(
        write_op: rados_write_op_t,
        key: *const ::std::os::raw::c_char,
        comparison_operator: u8,
        val: *const ::std::os::raw::c_char,
        key_len: usize,
        val_len: usize,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_setxattr(
        write_op: rados_write_op_t,
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
        value_len: usize,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_rmxattr(write_op: rados_write_op_t, name: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn rados_write_op_create(
        write_op: rados_write_op_t,
        exclusive: ::std::os::raw::c_int,
        category: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_write(
        write_op: rados_write_op_t,
        buffer: *const ::std::os::raw::c_char,
        len: usize,
        offset: u64,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_write_full(
        write_op: rados_write_op_t,
        buffer: *const ::std::os::raw::c_char,
        len: usize,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_writesame(
        write_op: rados_write_op_t,
        buffer: *const ::std::os::raw::c_char,
        data_len: usize,
        write_len: usize,
        offset: u64,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_append(
        write_op: rados_write_op_t,
        buffer: *const ::std::os::raw::c_char,
        len: usize,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_remove(write_op: rados_write_op_t);
}
unsafe extern "C" {
    pub fn rados_write_op_truncate(write_op: rados_write_op_t, offset: u64);
}
unsafe extern "C" {
    pub fn rados_write_op_zero(write_op: rados_write_op_t, offset: u64, len: u64);
}
unsafe extern "C" {
    pub fn rados_write_op_exec(
        write_op: rados_write_op_t,
        cls: *const ::std::os::raw::c_char,
        method: *const ::std::os::raw::c_char,
        in_buf: *const ::std::os::raw::c_char,
        in_len: usize,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_omap_set(
        write_op: rados_write_op_t,
        keys: *const *const ::std::os::raw::c_char,
        vals: *const *const ::std::os::raw::c_char,
        lens: *const usize,
        num: usize,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_omap_set2(
        write_op: rados_write_op_t,
        keys: *const *const ::std::os::raw::c_char,
        vals: *const *const ::std::os::raw::c_char,
        key_lens: *const usize,
        val_lens: *const usize,
        num: usize,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_omap_rm_keys(
        write_op: rados_write_op_t,
        keys: *const *const ::std::os::raw::c_char,
        keys_len: usize,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_omap_rm_keys2(
        write_op: rados_write_op_t,
        keys: *const *const ::std::os::raw::c_char,
        key_lens: *const usize,
        keys_len: usize,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_omap_rm_range2(
        write_op: rados_write_op_t,
        key_begin: *const ::std::os::raw::c_char,
        key_begin_len: usize,
        key_end: *const ::std::os::raw::c_char,
        key_end_len: usize,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_omap_clear(write_op: rados_write_op_t);
}
unsafe extern "C" {
    pub fn rados_write_op_set_alloc_hint(
        write_op: rados_write_op_t,
        expected_object_size: u64,
        expected_write_size: u64,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_set_alloc_hint2(
        write_op: rados_write_op_t,
        expected_object_size: u64,
        expected_write_size: u64,
        flags: u32,
    );
}
unsafe extern "C" {
    pub fn rados_write_op_operate(
        write_op: rados_write_op_t,
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        mtime: *mut time_t,
        flags: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_write_op_operate2(
        write_op: rados_write_op_t,
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        mtime: *mut timespec,
        flags: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_write_op_operate(
        write_op: rados_write_op_t,
        io: rados_ioctx_t,
        completion: rados_completion_t,
        oid: *const ::std::os::raw::c_char,
        mtime: *mut time_t,
        flags: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_write_op_operate2(
        write_op: rados_write_op_t,
        io: rados_ioctx_t,
        completion: rados_completion_t,
        oid: *const ::std::os::raw::c_char,
        mtime: *mut timespec,
        flags: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_create_read_op() -> rados_read_op_t;
}
unsafe extern "C" {
    pub fn rados_release_read_op(read_op: rados_read_op_t);
}
unsafe extern "C" {
    pub fn rados_read_op_set_flags(read_op: rados_read_op_t, flags: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn rados_read_op_assert_exists(read_op: rados_read_op_t);
}
unsafe extern "C" {
    pub fn rados_read_op_assert_version(read_op: rados_read_op_t, ver: u64);
}
unsafe extern "C" {
    pub fn rados_read_op_cmpext(
        read_op: rados_read_op_t,
        cmp_buf: *const ::std::os::raw::c_char,
        cmp_len: usize,
        off: u64,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_cmpxattr(
        read_op: rados_read_op_t,
        name: *const ::std::os::raw::c_char,
        comparison_operator: u8,
        value: *const ::std::os::raw::c_char,
        value_len: usize,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_getxattrs(
        read_op: rados_read_op_t,
        iter: *mut rados_xattrs_iter_t,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_omap_cmp(
        read_op: rados_read_op_t,
        key: *const ::std::os::raw::c_char,
        comparison_operator: u8,
        val: *const ::std::os::raw::c_char,
        val_len: usize,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_omap_cmp2(
        read_op: rados_read_op_t,
        key: *const ::std::os::raw::c_char,
        comparison_operator: u8,
        val: *const ::std::os::raw::c_char,
        key_len: usize,
        val_len: usize,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_stat(
        read_op: rados_read_op_t,
        psize: *mut u64,
        pmtime: *mut time_t,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_stat2(
        read_op: rados_read_op_t,
        psize: *mut u64,
        pmtime: *mut timespec,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_read(
        read_op: rados_read_op_t,
        offset: u64,
        len: usize,
        buffer: *mut ::std::os::raw::c_char,
        bytes_read: *mut usize,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_checksum(
        read_op: rados_read_op_t,
        type_: rados_checksum_type_t::Type,
        init_value: *const ::std::os::raw::c_char,
        init_value_len: usize,
        offset: u64,
        len: usize,
        chunk_size: usize,
        pchecksum: *mut ::std::os::raw::c_char,
        checksum_len: usize,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_exec(
        read_op: rados_read_op_t,
        cls: *const ::std::os::raw::c_char,
        method: *const ::std::os::raw::c_char,
        in_buf: *const ::std::os::raw::c_char,
        in_len: usize,
        out_buf: *mut *mut ::std::os::raw::c_char,
        out_len: *mut usize,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_exec_user_buf(
        read_op: rados_read_op_t,
        cls: *const ::std::os::raw::c_char,
        method: *const ::std::os::raw::c_char,
        in_buf: *const ::std::os::raw::c_char,
        in_len: usize,
        out_buf: *mut ::std::os::raw::c_char,
        out_len: usize,
        used_len: *mut usize,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_omap_get_vals(
        read_op: rados_read_op_t,
        start_after: *const ::std::os::raw::c_char,
        filter_prefix: *const ::std::os::raw::c_char,
        max_return: u64,
        iter: *mut rados_omap_iter_t,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_omap_get_vals2(
        read_op: rados_read_op_t,
        start_after: *const ::std::os::raw::c_char,
        filter_prefix: *const ::std::os::raw::c_char,
        max_return: u64,
        iter: *mut rados_omap_iter_t,
        pmore: *mut ::std::os::raw::c_uchar,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_omap_get_keys(
        read_op: rados_read_op_t,
        start_after: *const ::std::os::raw::c_char,
        max_return: u64,
        iter: *mut rados_omap_iter_t,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_omap_get_keys2(
        read_op: rados_read_op_t,
        start_after: *const ::std::os::raw::c_char,
        max_return: u64,
        iter: *mut rados_omap_iter_t,
        pmore: *mut ::std::os::raw::c_uchar,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_omap_get_vals_by_keys(
        read_op: rados_read_op_t,
        keys: *const *const ::std::os::raw::c_char,
        keys_len: usize,
        iter: *mut rados_omap_iter_t,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_omap_get_vals_by_keys2(
        read_op: rados_read_op_t,
        keys: *const *const ::std::os::raw::c_char,
        num_keys: usize,
        key_lens: *const usize,
        iter: *mut rados_omap_iter_t,
        prval: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn rados_read_op_operate(
        read_op: rados_read_op_t,
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        flags: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_read_op_operate(
        read_op: rados_read_op_t,
        io: rados_ioctx_t,
        completion: rados_completion_t,
        oid: *const ::std::os::raw::c_char,
        flags: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_lock_exclusive(
        io: rados_ioctx_t,
        oid: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        cookie: *const ::std::os::raw::c_char,
        desc: *const ::std::os::raw::c_char,
        duration: *mut timeval,
        flags: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_lock_shared(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        cookie: *const ::std::os::raw::c_char,
        tag: *const ::std::os::raw::c_char,
        desc: *const ::std::os::raw::c_char,
        duration: *mut timeval,
        flags: u8,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_unlock(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        cookie: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_aio_unlock(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        cookie: *const ::std::os::raw::c_char,
        completion: rados_completion_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_list_lockers(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        exclusive: *mut ::std::os::raw::c_int,
        tag: *mut ::std::os::raw::c_char,
        tag_len: *mut usize,
        clients: *mut ::std::os::raw::c_char,
        clients_len: *mut usize,
        cookies: *mut ::std::os::raw::c_char,
        cookies_len: *mut usize,
        addrs: *mut ::std::os::raw::c_char,
        addrs_len: *mut usize,
    ) -> isize;
}
unsafe extern "C" {
    pub fn rados_break_lock(
        io: rados_ioctx_t,
        o: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        client: *const ::std::os::raw::c_char,
        cookie: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_blocklist_add(
        cluster: rados_t,
        client_address: *mut ::std::os::raw::c_char,
        expire_seconds: u32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_blacklist_add(
        cluster: rados_t,
        client_address: *mut ::std::os::raw::c_char,
        expire_seconds: u32,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_getaddrs(
        cluster: rados_t,
        addrs: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_set_osdmap_full_try(io: rados_ioctx_t);
}
unsafe extern "C" {
    pub fn rados_unset_osdmap_full_try(io: rados_ioctx_t);
}
unsafe extern "C" {
    pub fn rados_set_pool_full_try(io: rados_ioctx_t);
}
unsafe extern "C" {
    pub fn rados_unset_pool_full_try(io: rados_ioctx_t);
}
unsafe extern "C" {
    pub fn rados_application_enable(
        io: rados_ioctx_t,
        app_name: *const ::std::os::raw::c_char,
        force: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_application_list(
        io: rados_ioctx_t,
        values: *mut ::std::os::raw::c_char,
        values_len: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_application_metadata_get(
        io: rados_ioctx_t,
        app_name: *const ::std::os::raw::c_char,
        key: *const ::std::os::raw::c_char,
        value: *mut ::std::os::raw::c_char,
        value_len: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_application_metadata_set(
        io: rados_ioctx_t,
        app_name: *const ::std::os::raw::c_char,
        key: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_application_metadata_remove(
        io: rados_ioctx_t,
        app_name: *const ::std::os::raw::c_char,
        key: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_application_metadata_list(
        io: rados_ioctx_t,
        app_name: *const ::std::os::raw::c_char,
        keys: *mut ::std::os::raw::c_char,
        key_len: *mut usize,
        values: *mut ::std::os::raw::c_char,
        vals_len: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_mon_command(
        cluster: rados_t,
        cmd: *mut *const ::std::os::raw::c_char,
        cmdlen: usize,
        inbuf: *const ::std::os::raw::c_char,
        inbuflen: usize,
        outbuf: *mut *mut ::std::os::raw::c_char,
        outbuflen: *mut usize,
        outs: *mut *mut ::std::os::raw::c_char,
        outslen: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_mgr_command(
        cluster: rados_t,
        cmd: *mut *const ::std::os::raw::c_char,
        cmdlen: usize,
        inbuf: *const ::std::os::raw::c_char,
        inbuflen: usize,
        outbuf: *mut *mut ::std::os::raw::c_char,
        outbuflen: *mut usize,
        outs: *mut *mut ::std::os::raw::c_char,
        outslen: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_mgr_command_target(
        cluster: rados_t,
        name: *const ::std::os::raw::c_char,
        cmd: *mut *const ::std::os::raw::c_char,
        cmdlen: usize,
        inbuf: *const ::std::os::raw::c_char,
        inbuflen: usize,
        outbuf: *mut *mut ::std::os::raw::c_char,
        outbuflen: *mut usize,
        outs: *mut *mut ::std::os::raw::c_char,
        outslen: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_mon_command_target(
        cluster: rados_t,
        name: *const ::std::os::raw::c_char,
        cmd: *mut *const ::std::os::raw::c_char,
        cmdlen: usize,
        inbuf: *const ::std::os::raw::c_char,
        inbuflen: usize,
        outbuf: *mut *mut ::std::os::raw::c_char,
        outbuflen: *mut usize,
        outs: *mut *mut ::std::os::raw::c_char,
        outslen: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_buffer_free(buf: *mut ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn rados_osd_command(
        cluster: rados_t,
        osdid: ::std::os::raw::c_int,
        cmd: *mut *const ::std::os::raw::c_char,
        cmdlen: usize,
        inbuf: *const ::std::os::raw::c_char,
        inbuflen: usize,
        outbuf: *mut *mut ::std::os::raw::c_char,
        outbuflen: *mut usize,
        outs: *mut *mut ::std::os::raw::c_char,
        outslen: *mut usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_pg_command(
        cluster: rados_t,
        pgstr: *const ::std::os::raw::c_char,
        cmd: *mut *const ::std::os::raw::c_char,
        cmdlen: usize,
        inbuf: *const ::std::os::raw::c_char,
        inbuflen: usize,
        outbuf: *mut *mut ::std::os::raw::c_char,
        outbuflen: *mut usize,
        outs: *mut *mut ::std::os::raw::c_char,
        outslen: *mut usize,
    ) -> ::std::os::raw::c_int;
}
pub type rados_log_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg: *mut ::std::os::raw::c_void,
        line: *const ::std::os::raw::c_char,
        who: *const ::std::os::raw::c_char,
        sec: u64,
        nsec: u64,
        seq: u64,
        level: *const ::std::os::raw::c_char,
        msg: *const ::std::os::raw::c_char,
    ),
>;
pub type rados_log_callback2_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg: *mut ::std::os::raw::c_void,
        line: *const ::std::os::raw::c_char,
        channel: *const ::std::os::raw::c_char,
        who: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        sec: u64,
        nsec: u64,
        seq: u64,
        level: *const ::std::os::raw::c_char,
        msg: *const ::std::os::raw::c_char,
    ),
>;
unsafe extern "C" {
    pub fn rados_monitor_log(
        cluster: rados_t,
        level: *const ::std::os::raw::c_char,
        cb: rados_log_callback_t,
        arg: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_monitor_log2(
        cluster: rados_t,
        level: *const ::std::os::raw::c_char,
        cb: rados_log_callback2_t,
        arg: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_service_register(
        cluster: rados_t,
        service: *const ::std::os::raw::c_char,
        daemon: *const ::std::os::raw::c_char,
        metadata_dict: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_service_update_status(
        cluster: rados_t,
        status_dict: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_objects_list_open(
        io: rados_ioctx_t,
        ctx: *mut rados_list_ctx_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_objects_list_get_pg_hash_position(ctx: rados_list_ctx_t) -> u32;
}
unsafe extern "C" {
    pub fn rados_objects_list_seek(ctx: rados_list_ctx_t, pos: u32) -> u32;
}
unsafe extern "C" {
    pub fn rados_objects_list_next(
        ctx: rados_list_ctx_t,
        entry: *mut *const ::std::os::raw::c_char,
        key: *mut *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rados_objects_list_close(ctx: rados_list_ctx_t);
}
